// src/logic/mmpi2/scaleLabels.ts

export const scaleLabels: Record<string, { en: string; pl?: string }> = {
  // Wskaźniki niespójności
  VRIN: { en: "Variable Response Inconsistency" /* , pl: "" */ },
  TRIN: { en: "True Response Inconsistency" /* , pl: "" */ },

  // Skale kontrolne i kliniczne
  L: { en: "Lie Scale" /* , pl: "" */ },
  F: { en: "Infrequency Scale" /* , pl: "" */ },
  Fb: { en: "Back Infrequency" /* , pl: "" */ },
  Fp: { en: "Infrequency-Psychopathology" /* , pl: "" */ },
  K: { en: "Correction Scale (Defensiveness)" /* , pl: "" */ },
  S: { en: "Superlative Self-Presentation" /* , pl: "" */ },

  Hs: { en: "Hypochondriasis" /* , pl: "" */ },
  D: { en: "Depression" /* , pl: "" */ },
  Hy: { en: "Hysteria" /* , pl: "" */ },
  Pd: { en: "Psychopathic Deviate" /* , pl: "" */ },
  Mf: { en: "Masculinity-Femininity" /* , pl: "" */ },
  Pa: { en: "Paranoia" /* , pl: "" */ },
  Pt: { en: "Psychasthenia" /* , pl: "" */ },
  Sc: { en: "Schizophrenia" /* , pl: "" */ },
  Ma: { en: "Hypomania" /* , pl: "" */ },
  Si: { en: "Social Introversion" /* , pl: "" */ },

  // Skale treściowe (Content Scales)
  ANG: { en: "Anger" /* , pl: "" */ },
  ANX: { en: "Anxiety" /* , pl: "" */ },
  ASP: { en: "Antisocial Practices" /* , pl: "" */ },
  BIZ: { en: "Bizarre Mentation" /* , pl: "" */ },
  CYN: { en: "Cynicism" /* , pl: "" */ },
  DEP: { en: "Depression" /* , pl: "" */ },
  FAM: { en: "Family Problems" /* , pl: "" */ },
  FRS: { en: "Fears" /* , pl: "" */ },
  HEA: { en: "Health Concerns" /* , pl: "" */ },
  LSE: { en: "Low Self-Esteem" /* , pl: "" */ },
  OBS: { en: "Obsessiveness" /* , pl: "" */ },
  SOD: { en: "Social Discomfort" /* , pl: "" */ },
  TPA: { en: "Type A Behavior" /* , pl: "" */ },
  TRT: { en: "Negative Treatment Indicators" /* , pl: "" */ },
  WRK: { en: "Work Interference" /* , pl: "" */ },

  // Podskale treściowe
  ANG1: { en: "Explosive Behavior" /* , pl: "" */ },
  ANG2: { en: "Irritability" /* , pl: "" */ },
  ASP1: { en: "Antisocial Attitudes" /* , pl: "" */ },
  ASP2: { en: "Antisocial Behavior" /* , pl: "" */ },
  BIZ1: { en: "Schizotypal Characteristics" /* , pl: "" */ },
  BIZ2: { en: "Psychotic Experiences" /* , pl: "" */ },
  CYN1: { en: "Misanthropic Beliefs" /* , pl: "" */ },
  CYN2: { en: "Interpersonal Suspicion" /* , pl: "" */ },
  DEP1: { en: "Lack of Drive" /* , pl: "" */ },
  DEP2: { en: "Dysphoria" /* , pl: "" */ },
  DEP3: { en: "Self-Deprecation" /* , pl: "" */ },
  DEP4: { en: "Sense of Failure" /* , pl: "" */ },
  FAM1: { en: "Familial Alienation" /* , pl: "" */ },
  FAM2: { en: "Family Discord" /* , pl: "" */ },
  FRS1: { en: "Generalized Fears" /* , pl: "" */ },
  FRS2: { en: "Multiple Fears" /* , pl: "" */ },
  HEA1: { en: "Gastrointestinal Symptoms" /* , pl: "" */ },
  HEA2: { en: "Neurological Symptoms" /* , pl: "" */ },
  HEA3: { en: "General Health Concerns" /* , pl: "" */ },
  LSE1: { en: "Self-Doubt" /* , pl: "" */ },
  LSE2: { en: "Submissiveness" /* , pl: "" */ },
  SOD1: { en: "Introversion" /* , pl: "" */ },
  SOD2: { en: "Shyness" /* , pl: "" */ },
  TPA1: { en: "Impatience" /* , pl: "" */ },
  TPA2: { en: "Competitive Drive" /* , pl: "" */ },
  TRT1: { en: "Low Motivation" /* , pl: "" */ },
  TRT2: { en: "Inability to Disclose" /* , pl: "" */ },

  // Skale dodatkowe
  A: { en: "Anxiety" /* , pl: "" */ },
  R: { en: "Repression" /* , pl: "" */ },
  Es: { en: "Ego Strength" /* , pl: "" */ },
  Do: { en: "Dominance" /* , pl: "" */ },
  Re: { en: "Responsibility" /* , pl: "" */ },
  Mt: { en: "College Maladjustment" /* , pl: "" */ },
  PK: { en: "Post-Traumatic Stress Disorder" /* , pl: "" */ },
  MDS: { en: "Marital Distress Scale" /* , pl: "" */ },
  Ho: { en: "Hostility" /* , pl: "" */ },
  "O-H": { en: "Overcontrolled Hostility" /* , pl: "" */ },
  "MAC-R": { en: "MacAndrew Alcoholism Scale – Revised" /* , pl: "" */ },
  AAS: { en: "Addiction Acknowledgement Scale" /* , pl: "" */ },
  APS: { en: "Addiction Potential Scale" /* , pl: "" */ },
  GM: { en: "Masculine Gender Role" /* , pl: "" */ },
  GF: { en: "Feminine Gender Role" /* , pl: "" */ },

  // Skale Harris-Lingoes
  Hs1: { en: "Somatic Complaints" /* , pl: "Skargi somatyczne" */ },
  Hs2: { en: "Poor Physical Health" /* , pl: "Złe zdrowie fizyczne" */ },
  D1: { en: "Subjective Depression" /* , pl: "Subiektywna depresja" */ },
  D2: { en: "Psychomotor Retardation" /* , pl: "Spowolnienie psychoruchowe" */ },
  D3: { en: "Physical Malfunctioning" /* , pl: "Zaburzenia fizyczne" */ },
  D4: { en: "Mental Dullness" /* , pl: "Otępienie umysłowe" */ },
  D5: { en: "Brooding" /* , pl: "Rozpamiętywanie" */ },
  Hy1: { en: "Denial of Social Anxiety" /* , pl: "Zaprzeczanie lękowi społecznemu" */ },
  Hy2: { en: "Need for Affection" /* , pl: "Potrzeba akceptacji" */ },
  Hy3: { en: "Lassitude-Malaise" /* , pl: "Znużenie i apatia" */ },
  Hy4: { en: "Somatic Complaints" /* , pl: "Skargi somatyczne" */ },
  Hy5: { en: "Inhibition of Aggression" /* , pl: "Hamowanie agresji" */ },
  Pd1: { en: "Familial Discord" /* , pl: "Nieporozumienia rodzinne" */ },
  Pd2: { en: "Authority Problems" /* , pl: "Problemy z autorytetami" */ },
  Pd3: { en: "Social Imperturbability" /* , pl: "Brak lęku społecznego" */ },
  Pd4: { en: "Social Alienation" /* , pl: "Alienacja społeczna" */ },
  Pd5: { en: "Self-Alienation" /* , pl: "Autoalienacja" */ },
  Pa1: { en: "Persecutory Ideas" /* , pl: "Prześladowcze idee" */ },
  Pa2: { en: "Poignancy" /* , pl: "Wrażliwość" */ },
  Pa3: { en: "Naiveté" /* , pl: "Naiwność" */ },
  Sc1: { en: "Social Alienation" /* , pl: "Alienacja społeczna" */ },
  Sc2: { en: "Emotional Alienation" /* , pl: "Alienacja emocjonalna" */ },
  Sc3: { en: "Lack of Ego Mastery, Cognitive" /* , pl: "Brak kontroli ego – funkcje poznawcze" */ },
  Sc4: { en: "Lack of Ego Mastery, Conative" /* , pl: "Brak kontroli ego – działanie" */ },
  Sc5: { en: "Lack of Ego Mastery, Defective Inhibition" /* , pl: "Brak kontroli ego – deficyt hamowania" */ },
  Sc6: { en: "Bizarre Sensory Experiences" /* , pl: "Dziwaczne doświadczenia sensoryczne" */ },
  Ma1: { en: "Amorality" /* , pl: "Amoralność" */ },
  Ma2: { en: "Psychomotor Acceleration" /* , pl: "Przyspieszenie psychoruchowe" */ },
  Ma3: { en: "Imperturbability" /* , pl: "Nieporuszoność" */ },
  Ma4: { en: "Ego Inflation" /* , pl: "Nadmierne ego" */ },

// Skale zrestrukturyzowane
  RCd: { en: "Demoralization" /* , pl: "" */ },
  RC1: { en: "Somatic Complaints" /* , pl: "" */ },
  RC2: { en: "Low Positive Emotions" /* , pl: "" */ },
  RC3: { en: "Cynicism" /* , pl: "" */ },
  RC4: { en: "Antisocial Behavior" /* , pl: "" */ },
  RC6: { en: "Ideas of Persecution" /* , pl: "" */ },
  RC7: { en: "Dysfunctional Negative Emotions" /* , pl: "" */ },
  RC8: { en: "Aberrant Experiences" /* , pl: "" */ },
  RC9: { en: "Hypomanic Activation" /* , pl: "" */ }
};
