// src/logic/mmpi2/scaleLabels.ts

export const scaleLabels: Record<string, { en: string; pl?: string }> = {
  // Wskaźniki niespójności
  VRIN: { en: "Variable Response Inconsistency", pl: "Skala Niespójności Odpowiedzi Niezgodnych" },
  TRIN: { en: "True Response Inconsistency", pl: "Skala Niespójności Odpowiedzi Zgodnych" },

  // Skale kontrolne i kliniczne
  "?": { en: "Number of omitted responses", pl: "Nie wiem" },
  L: { en: "Lie Scale", pl: "Skala Kłamstwa" },
  F: { en: "Infrequency Scale", pl: "Skala Odpowiedzi Rzadkich" },
  Fb: { en: "Back Infrequency", pl: "Skala Odpowiedzi Rzadkich dla Dalszej Części Testu" },
  Fp: { en: "Infrequency-Psychopathology", pl: "Skala Odpowiedzi Rzadkich Dotyczących Objawów Psychopatologicznych" },
  K: { en: "Correction Scale (Defensiveness)", pl: "Skala Korekcyjna" },
  S: { en: "Superlative Self-Presentation", pl: "Skala Pozytywnej Autoprezentacji" },

  Hs: { en: "Hypochondriasis", pl: "Skala Hipochondrii" },
  D: { en: "Depression", pl: "Skala Depresji" },
  Hy: { en: "Hysteria", pl: "Skala Histerii" },
  Pd: { en: "Psychopathic Deviate", pl: "Skala Odchyleń Psychopatycznych" },
  Mf: { en: "Masculinity-Femininity", pl: "Skala Męskości-Kobiecości" },
  Pa: { en: "Paranoia", pl: "Skala Paranoi" },
  Pt: { en: "Psychasthenia", pl: "Skala Psychastenii" },
  Sc: { en: "Schizophrenia", pl: "Skala Schizofrenii" },
  Ma: { en: "Hypomania", pl: "Skala Hipomanii" },
  Si: { en: "Social Introversion", pl: "Skala Introwersji Społecznej" },

  // Skale treściowe (Content Scales)
  ANG: { en: "Anger", pl: "Skala Złości" },
  ANX: { en: "Anxiety", pl: "Skala Uogólnionego Niepokoju" },
  ASP: { en: "Antisocial Practices", pl: "Skala Postaw i Zachowań Antyspołecznych" },
  BIZ: { en: "Bizarre Mentation", pl: "Skala Dziwacznego Myślenia" },
  CYN: { en: "Cynicism", pl: "Skala Cynizmu" },
  DEP: { en: "Depression", pl: "Skala Depresji" },
  FAM: { en: "Family Problems", pl: "Skala Problemów Rodzinnych" },
  FRS: { en: "Fears", pl: "Skala Lęków" },
  HEA: { en: "Health Concerns", pl: "Skala Troski o Zdrowie" },
  LSE: { en: "Low Self-Esteem", pl: "Skala Niskiej Samooceny" },
  OBS: { en: "Obsessiveness", pl: "Skala Obsesyjności" },
  SOD: { en: "Social Discomfort", pl: "Skala Dyskomfortu Społecznego" },
  TPA: { en: "Type A Behavior", pl: "Skala Typ Zachowania A" },
  TRT: { en: "Negative Treatment Indicators", pl: "Skala Negatywnego Nastawienia Wobec Terapii" },
  WRK: { en: "Work Interference", pl: "Skala Zakłócenia w Pracy" },

  // Podskale treściowe
  ANG1: { en: "Explosive Behavior", pl: "Skala Wybuchowego Zachowania" },
  ANG2: { en: "Irritability", pl: "Skala Drażliwości" },
  ASP1: { en: "Antisocial Attitudes", pl: "Skala Postaw Antyspołecznych" },
  ASP2: { en: "Antisocial Behavior", pl: "Skala Zachowań Antyspołecznych" },
  BIZ1: { en: "Schizotypal Characteristics", pl: "Skala Cech Schizotypowych" },
  BIZ2: { en: "Psychotic Experiences", pl: "Skala Symptomów Psychotycznych" },
  CYN1: { en: "Misanthropic Beliefs", pl: "Skala Mizantropijnych Przekonań" },
  CYN2: { en: "Interpersonal Suspicion", pl: "Skala Podejrzliwości Interpersonalnej" },
  DEP1: { en: "Lack of Drive", pl: "Skala Braku Energii" },
  DEP2: { en: "Dysphoria", pl: "Skala Dysforii" },
  DEP3: { en: "Self-Deprecation", pl: "Skala Autodeprecjacji" },
  DEP4: { en: "Sense of Failure", pl: "Skala Myśli Samobójczych" },
  FAM1: { en: "Familial Alienation", pl: "Skala Niezgody w Rodzinie" },
  FAM2: { en: "Family Discord", pl: "Skala Wyobcowania z Rodziny" },
  FRS1: { en: "Generalized Fears", pl: "Skala Ogólnej Lękliwości" },
  FRS2: { en: "Multiple Fears", pl: "Skala Różnorakich Lęków" },
  HEA1: { en: "Gastrointestinal Symptoms", pl: "Skala Objawów Żołądkowo-Jelitowych" },
  HEA2: { en: "Neurological Symptoms", pl: "Skala Objawów Neurologicznych" },
  HEA3: { en: "General Health Concerns", pl: "Skala Ogólnego Niepokoju o Zdrowie" },
  LSE1: { en: "Self-Doubt", pl: "Skala Braku Wiary w Siebie" },
  LSE2: { en: "Submissiveness", pl: "Skala Uległości" },
  SOD1: { en: "Introversion", pl: "Skala Introwersji" },
  SOD2: { en: "Shyness", pl: "Skala Nieśmiałości" },
  TPA1: { en: "Impatience", pl: "Skala Niecierpliwości" },
  TPA2: { en: "Competitive Drive", pl: "Skala Tendencji Rywalizacyjnych" },
  TRT1: { en: "Low Motivation", pl: "Skala Niskiej Motywacji" },
  TRT2: { en: "Inability to Disclose", pl: "Skala Braku Otwartości" },

  // Skale dodatkowe
  A: { en: "Anxiety", pl: "Skala Niepokoju" },
  R: { en: "Repression", pl: "Skala Represji" },
  Es: { en: "Ego Strength", pl: "Skala Siły Ego" },
  Do: { en: "Dominance", pl: "Skala Dominacji" },
  Re: { en: "Responsibility", pl: "Skala Odpowiedzialności Społecznej" },
  Mt: { en: "College Maladjustment", pl: "Skala Nieprzystosowania do Szkoły" },
  PK: { en: "Post-Traumatic Stress Disorder", pl: "Zespół Stresu Pourazowego" },
  MDS: { en: "Marital Distress Scale", pl: "Skala Dyssatysfakcji Małżeńskiej" },
  Ho: { en: "Hostility", pl: "Skala Wrogości" },
  "O-H": { en: "Overcontrolled Hostility", pl: "Skala Nadmiernie Kontrolowanej Wrogości" },
  "MAC-R": { en: "MacAndrew Alcoholism Scale – Revised", pl: "Zrewidowana Skala Alkoholizmu MacAdrew" },
  AAS: { en: "Addiction Acknowledgement Scale", pl: "Skala Przyznawania Się do Uzależnienia" },
  APS: { en: "Addiction Potential Scale", pl: "Skala Potencjalnego Uzależnienia" },
  GM: { en: "Masculine Gender Role", pl: "Skala Roli Związanej z Płcią Męską" },
  GF: { en: "Feminine Gender Role", pl: "Skala Roli Związanej z Płcią Kobiecą" },

  // Skale Harrisa-Lingoesa
  D1: { en: "Subjective Depression", pl: "Skala Subiektywnego Poczucia Depresji" },
  D2: { en: "Psychomotor Retardation", pl: "Skala Spowolnienia Psychoruchowego" },
  D3: { en: "Physical Malfunctioning", pl: "Skala Dolegliwości Fizycznych" },
  D4: { en: "Mental Dullness", pl: "Skala Otępienia Psychicznego" },
  D5: { en: "Brooding", pl: "Skala Pogrążania Się w Ponurych Rozmyślaniach" },
  Hy1: { en: "Denial of Social Anxiety", pl: "Skala Zaprzeczania Lękowi Społecznemu" },
  Hy2: { en: "Need for Affection", pl: "Skala Potrzeby Kontaktu Społecznego" },
  Hy3: { en: "Lassitude-Malaise", pl: "Skala Zmęczenia-Złego Samopoczucia" },
  Hy4: { en: "Somatic Complaints", pl: "Skala Skarg Somatycznych" },
  Hy5: { en: "Inhibition of Aggression", pl: "Skala Hamowania Agresji" },
  Pd1: { en: "Familial Discord", pl: "Skala Konfliktów w Rodzinie" },
  Pd2: { en: "Authority Problems", pl: "Skala Negatywnego Stosunku Wobec Autorytetów" },
  Pd3: { en: "Social Imperturbability", pl: "Skala Odporności na Wpływ Społeczny" },
  Pd4: { en: "Social Alienation", pl: "Skala Alienacji Społecznej" },
  Pd5: { en: "Self-Alienation", pl: "Skala Autoalienacji" },
  Pa1: { en: "Persecutory Ideas", pl: "Skala Myśli Prześladowczych" },
  Pa2: { en: "Poignancy", pl: "Skala Przewrażliwienia" },
  Pa3: { en: "Naivete", pl: "Skala Naiwności" },
  Sc1: { en: "Social Alienation", pl: "Skala Alienacji Społecznej" },
  Sc2: { en: "Emotional Alienation", pl: "Skala Alienacji Emocjonalnej" },
  Sc3: { en: "Lack of Ego Mastery, Cognitive", pl: "Skala Braku Panowania Ego w Sferze Poznawczej" },
  Sc4: { en: "Lack of Ego Mastery, Conative", pl: "Skala Braku Panowania Ego w Sferze Wolicjonalnej" },
  Sc5: { en: "Lack of Ego Mastery, Defective Inhibition", pl: "Skala Braku Panowania Ego w Sferze Kontroli" },
  Sc6: { en: "Bizarre Sensory Experiences", pl: "Skala Dziwacznych Doznań Sensorycznych" },
  Ma1: { en: "Amoral Attitudes", pl: "Skala Amoralności" },
  Ma2: { en: "Psychomotor Acceleration", pl: "Skala Pobudzenia Psychoruchowego" },
  Ma3: { en: "Imperturbability", pl: "Skala Niewrażliwości na Opinię Społeczną" },
  Ma4: { en: "Ego Inflation", pl: "Skala Inflacji Ego" },

  // Skale RC
  RCd: { en: "Demoralization", pl: "Skala Zniechęcenia" },
  RC1: { en: "Somatic Complaints", pl: "Skala Skargi Somatyczne" },
  RC2: { en: "Low Positive Emotions", pl: "Skala Niedostatku Emocji Pozytywnych" },
  RC3: { en: "Cynicism", pl: "Skala Cynizmu" },
  RC4: { en: "Antisocial Behavior", pl: "Skala Zachowania Antyspołecznego" },
  RC6: { en: "Ideas of Persecution", pl: "Skala Myśli Prześladowczych" },
  RC7: { en: "Dysfunctional Negative Emotions", pl: "Skala Dysfunkcjonalnych Negatywnych Emocji" },
  RC8: { en: "Aberrant Experiences", pl: "Skala Nietypowych Przeżyć" },
  RC9: { en: "Hypomanic Activation", pl: "Skala Pobudzenia Hipomaniakalnego" },

  // Podskale Si
  Si1: { en: "Shyness/Self-Consciousness", pl: "Skala Nieśmiałości" },
  Si2: { en: "Social Avoidance", pl: "Skala Społecznego Unikania" },
  Si3: { en: "Self/Other Alienation", pl: "Skala Alienacji" },

  // Brakujące skale z Twojej listy
  AGGR: { en: "Aggressiveness", pl: "Agresywności" },
  DISC: { en: "Disconstraint", pl: "Braku Zahamowań" },
  INTR: { en: "Introversion/Low Positive Emotionality", pl: "Introwersji/Niskiej Pozytywnej Emocjonalności" },
  NEGE: { en: "Negative Emotionality/Neuroticism", pl: "Negatywnej Emocjonalności/Neurotyczności" },
  PSYC: { en: "Psychoticism", pl: "Psychotyzmu" }
};
